local STRINGS = GLOBAL.STRINGS

STRINGS.AQ_AUTOCOLLECT = "자동 줍기 : "

STRINGS.AQ_AUTOCOLLECT_CHOP = "벌목 모드"

STRINGS.AQ_AUTOCOLLECT_NORMAL = "기본"

STRINGS.AQ_ENDLESSDEPLOY = "자동 설치 : "

STRINGS.AQ_NORECIPEFOUND = "최근 제작 없음"

STRINGS.AQ_UNABLECRAFT = "만들 수 없음 : "

STRINGS.AQ_CRAFTLAST = "최근 제작 : "

STRINGS.AQ_TRUE = "켜짐"

STRINGS.AQ_FALSE = "꺼짐"