local STRINGS = GLOBAL.STRINGS

STRINGS.AQ_AUTOCOLLECT = "自动拾取 : "

STRINGS.AQ_AUTOCOLLECT_CHOP = "砍树模式"

STRINGS.AQ_AUTOCOLLECT_NORMAL = "正常模式"

STRINGS.AQ_ENDLESSDEPLOY = "无尽部署 : "

STRINGS.AQ_NORECIPEFOUND = "未找到上次制作的配方"

STRINGS.AQ_UNABLECRAFT = "无法制作 : "

STRINGS.AQ_CRAFTLAST = "制作最后一次的配方 : "

STRINGS.AQ_TRUE = "启用"

STRINGS.AQ_FALSE = "禁用"